### ISSUE TITLE
Something goes wrong

### ISSUE THREAD

**Issue by HeToC** [kmees/spfx-react-mobx-webpart-starter#1]
[SPWebPartErrorCode.ScriptLoadError]:: MESSAGE:: Unable to load web part WebPart.FaceBoardWebPart.7c06c944-3398-4fcf-8e3f-d75feda78766,Error: Error: [mobx] An incompatible version of mobservable is already loaded.

**Comment by kevicency** [comment]
Try using the `mobx@2.7.0-beta` version of mobx https://github.com/mobxjs/mobx/issues/621

**Comment by mweststrate** [comment]
@kmees MobX 3.0 has been released which contains this patch, so you might want to upgrade your deps.
